import { BIDS } from "@/lib/mock/bids";
import { TEAM } from "@/lib/mock/team";
import { DEFAULT_PINNED_IDS, VAULT_ARTIFACTS } from "@/lib/mock/vault";
import type { Bid, Workspace } from "./types";
import { alert, documentFromBid, matrixFromDocument, nowIso, valueMidFromRange } from "./helpers";

const PINNED = new Set<string>(DEFAULT_PINNED_IDS);

function hydrateBid(bid: (typeof BIDS)[number], extra?: Partial<Bid>): Bid {
  return {
    ...bid,
    valueMid: valueMidFromRange(bid.value),
    source: "seed",
    pinned: PINNED.has(bid.id),
    crmSynced: bid.id === "it-infra" ? "salesforce" : null,
    createdAt: "2026-07-01T12:00:00.000Z",
    ...extra,
  };
}

export const SAM_FEED: Bid[] = [
  {
    id: "nasa-hpc",
    title: "High-Performance Computing Sustainment",
    rfpId: "RFP-2026-NASA-044",
    agency: "NASA",
    jurisdiction: "Federal Government",
    value: "$6M – $9M",
    valueMid: 7.5,
    duration: "4 years",
    bidders: 8,
    due: "Oct 21, 2026",
    winProbability: 58,
    status: "hot",
    highlight: "Matches your 541512 NAICS and IL5 past performance.",
    naics: "541512",
    setAside: "Unrestricted",
    source: "discovery",
    pinned: false,
    crmSynced: null,
    createdAt: nowIso(),
  },
  {
    id: "army-net",
    title: "Tactical Network Modernization",
    rfpId: "RFP-2026-ARMY-118",
    agency: "Department of the Army",
    jurisdiction: "Federal Government",
    value: "$18M – $24M",
    valueMid: 21,
    duration: "5 years",
    bidders: 11,
    due: "Nov 3, 2026",
    winProbability: 47,
    status: "analyzing",
    highlight: "Sources-sought comments close Friday. C5ISR overlay required.",
    naics: "541512",
    setAside: "Unrestricted",
    source: "discovery",
    pinned: false,
    crmSynced: null,
    createdAt: nowIso(),
  },
  {
    id: "ca-cyber",
    title: "Statewide Cyber Defense Operations",
    rfpId: "RFP-2026-CA-033",
    agency: "State of California",
    jurisdiction: "State Government",
    value: "$3M – $5M",
    valueMid: 4,
    duration: "3 years",
    bidders: 16,
    due: "Oct 12, 2026",
    winProbability: 39,
    status: "watching",
    highlight: "Small-business set-aside. SOC 2 Type II asked in Section L.",
    naics: "541513",
    setAside: "Small Business",
    source: "discovery",
    pinned: false,
    crmSynced: null,
    createdAt: nowIso(),
  },
  {
    id: "gsa-oasis",
    title: "OASIS+ Domain 3 Digital Services",
    rfpId: "RFP-2026-GSA-901",
    agency: "General Services Administration",
    jurisdiction: "Federal Government",
    value: "$9M – $14M",
    valueMid: 11.5,
    duration: "5 years",
    bidders: 22,
    due: "Dec 15, 2026",
    winProbability: 44,
    status: "qualified",
    highlight: "On-ramp window. Your GSA vehicle list is a discriminator.",
    naics: "541511",
    setAside: "Unrestricted",
    source: "discovery",
    pinned: false,
    crmSynced: null,
    createdAt: nowIso(),
  },
  {
    id: "hhs-data",
    title: "HHS Data Lake & Interoperability",
    rfpId: "RFP-2026-HHS-077",
    agency: "Department of Health and Human Services",
    jurisdiction: "Federal Government",
    value: "$7M – $11M",
    valueMid: 9,
    duration: "4 years",
    bidders: 9,
    due: "Nov 20, 2026",
    winProbability: 63,
    status: "hot",
    highlight: "FHIR / TEFCA language mirrors your VA EHR write-up.",
    naics: "541511",
    setAside: "Unrestricted",
    source: "discovery",
    pinned: false,
    crmSynced: null,
    createdAt: nowIso(),
  },
  {
    id: "dot-its",
    title: "Intelligent Transportation Systems Backbone",
    rfpId: "RFP-2026-DOT-210",
    agency: "Department of Transportation",
    jurisdiction: "Federal Government",
    value: "$4M – $6M",
    valueMid: 5,
    duration: "3 years",
    bidders: 13,
    due: "Oct 8, 2026",
    winProbability: 36,
    status: "due",
    highlight: "Questions due in 4 days. 508 and CISA crosswalk required.",
    naics: "541512",
    setAside: "Unrestricted",
    source: "discovery",
    pinned: false,
    crmSynced: null,
    createdAt: nowIso(),
  },
];

export function buildSeedWorkspace(): Workspace {
  const bids = BIDS.map((bid) => hydrateBid(bid));
  const documents = bids.map((bid) => documentFromBid(bid));
  const matrix = documents.flatMap((doc, index) => matrixFromDocument(bids[index], doc));

  return {
    bids,
    documents,
    matrix,
    scores: [
      {
        bidId: "it-infra",
        decision: "go",
        score: 78,
        reasons: [
          { label: "NAICS / vehicle fit", score: 88, note: "541512 is a core code on the capability profile." },
          { label: "Past performance", score: 82, note: "DoD IT sustainment CPARS maps cleanly." },
          { label: "Competitive pressure", score: 61, note: "12 bidders. Incumbent is protest-prone." },
          { label: "Capacity", score: 74, note: "Capture cell has a writer and architect free after orals." },
        ],
        updatedAt: "2026-08-01T12:00:00.000Z",
      },
    ],
    proposals: [
      {
        id: "pr-it-vol1",
        bidId: "it-infra",
        title: "Volume I — Technical Approach",
        volume: "Volume I",
        body: "Draft technical approach for IT Infrastructure Upgrade. Discriminators: IL5 boundary, 30-day transition, zero Level III CARs on the last DoD vehicle.",
        status: "draft",
        updatedAt: "2026-08-12T12:00:00.000Z",
      },
    ],
    artifacts: VAULT_ARTIFACTS.map((file) => ({ ...file })),
    team: TEAM.map((member) => ({ ...member })),
    alerts: [
      alert({
        title: "Pre-bid conference",
        body: "IT Infrastructure Upgrade — join from the analyzer.",
        href: "/dashboard/analyzer/it-infra",
        kind: "deadline",
      }),
      alert({
        title: "Questions due Friday",
        body: "Federal Cloud Migration Vehicle. IL5 boundary language is still open.",
        href: "/dashboard/analyzer/cloud-mig",
        kind: "deadline",
      }),
      alert({
        title: "New artifact in Vault",
        body: "Price workbook FY26 was checked in by Pricing.",
        href: "/dashboard/vault",
        kind: "team",
      }),
    ],
    connectors: [
      { id: "salesforce", name: "Salesforce", description: "Create Opportunities from qualified RFPs.", connected: true, webhook: "https://hooks.winroom.ai/salesforce", lastSync: "2026-09-08T18:00:00.000Z", lastCount: 4 },
      { id: "hubspot", name: "HubSpot", description: "Sync companies, deals, and capture notes.", connected: false, webhook: "https://hooks.winroom.ai/hubspot" },
      { id: "dynamics", name: "Dynamics 365", description: "Push bids into the government pipeline view.", connected: false, webhook: "https://hooks.winroom.ai/dynamics" },
      { id: "pipedrive", name: "Pipedrive", description: "Keep the capture desk in the same dealboard.", connected: false, webhook: "https://hooks.winroom.ai/pipedrive" },
      { id: "slack", name: "Slack", description: "Deadline and discovery alerts to #capture.", connected: true, webhook: "https://hooks.winroom.ai/slack", lastSync: "2026-09-09T06:00:00.000Z", lastCount: 12 },
      { id: "sharepoint", name: "SharePoint", description: "Drop volumes into the controlled library.", connected: false, webhook: "https://hooks.winroom.ai/sharepoint" },
    ],
    automations: [
      { id: "discovery", name: "Nightly SAM discovery", description: "Match new notices to your NAICS, vehicles, and keywords.", enabled: true, cadence: "Every night 02:00 ET", lastRun: "2026-09-09T06:00:00.000Z", lastResult: "6 notices scored" },
      { id: "deadlines", name: "Deadline watcher", description: "Alert when questions or proposals are inside 10 days.", enabled: true, cadence: "Hourly", lastRun: "2026-09-09T09:00:00.000Z", lastResult: "2 deadlines flagged" },
      { id: "analyze", name: "Auto-analyze new RFPs", description: "Extract shall-statements and draft a go/no-go when a bid lands.", enabled: true, cadence: "On ingest", lastRun: "2026-09-08T16:40:00.000Z", lastResult: "Matrix built for 1 bid" },
      { id: "crm", name: "CRM push for qualified bids", description: "Sync qualified / hot bids to the connected CRM.", enabled: false, cadence: "On status change", lastResult: "Idle — turn on after HubSpot connect" },
    ],
    workflows: [
      {
        id: "sprint",
        name: "Capture sprint",
        description: "Discover → score → assign → draft → sync CRM",
        status: "idle",
        nodes: [
          { id: "discover", label: "Discover", status: "pending" },
          { id: "score", label: "Score", status: "pending" },
          { id: "assign", label: "Assign team", status: "pending" },
          { id: "draft", label: "Draft volume", status: "pending" },
          { id: "sync", label: "Sync CRM", status: "pending" },
        ],
      },
      {
        id: "color",
        name: "Color review pack",
        description: "Build matrix, insights, and Volume I outline for pink/red review.",
        status: "idle",
        nodes: [
          { id: "matrix", label: "Compliance matrix", status: "pending" },
          { id: "insights", label: "Win themes", status: "pending" },
          { id: "outline", label: "Volume outline", status: "pending" },
          { id: "share", label: "Share to vault", status: "pending" },
        ],
      },
    ],
    profile: {
      name: "Winroom Federal",
      naics: ["541512", "541511", "541513"],
      vehicles: ["GSA MAS", "OASIS+", "CIO-SP4"],
      geos: ["CONUS", "NCR", "Arizona"],
      clearance: "Secret / IL5 facilities",
      keywords: ["FedRAMP", "IL5", "SOC", "EHR", "cloud migration"],
      pastPerformance: "DoD IT sustainment (Exceptional CPARS), VA FHIR interoperability, GSA cloud migration support.",
    },
    billing: {
      plan: "desk",
      seats: 12,
      rfpQuota: 80,
      rfpsUsed: BIDS.length,
    },
    leads: [],
    audit: [{ id: "aud_seed", at: "2026-09-01T12:00:00.000Z", action: "Workspace initialized with live capture seed." }],
  };
}
